"""initial schema

Revision ID: cc1aba6709c1
Revises: 
Create Date: 2026-03-18 01:07:36.705636

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cc1aba6709c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('corridors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('public_holidays',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('saccos',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.Enum('SEATER_14', 'SEATER_32', 'SEATER_52', 'ELECTRIC', name='vehicletype'), nullable=False),
    sa.Column('is_electric', sa.Boolean(), nullable=False),
    sa.Column('terminus_area', sa.String(length=100), nullable=True),
    sa.Column('operating_status', sa.Enum('ACTIVE', 'SUSPENDED', 'SEASONAL', name='operatingstatus'), nullable=False),
    sa.Column('safety_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('comfort_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('search_logs',
    sa.Column('origin_text', sa.String(length=200), nullable=False),
    sa.Column('destination_text', sa.String(length=200), nullable=False),
    sa.Column('resolved_origin_id', sa.UUID(), nullable=True),
    sa.Column('resolved_dest_id', sa.UUID(), nullable=True),
    sa.Column('result_count', sa.SmallInteger(), nullable=False),
    sa.Column('had_transfer', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('queried_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('landmark', sa.String(length=300), nullable=True),
    sa.Column('landmark_sw', sa.String(length=300), nullable=True),
    sa.Column('stage_type', sa.Enum('FORMAL', 'INFORMAL', name='stagetype'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'BOTH', name='direction'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corridor_surges',
    sa.Column('corridor_id', sa.UUID(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('reason_sw', sa.String(length=200), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('sacco_id', sa.UUID(), nullable=False),
    sa.Column('corridor_id', sa.UUID(), nullable=True),
    sa.Column('origin_stage_id', sa.UUID(), nullable=False),
    sa.Column('dest_stage_id', sa.UUID(), nullable=False),
    sa.Column('via_description', sa.String(length=200), nullable=True),
    sa.Column('via_description_sw', sa.String(length=200), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_express', sa.Boolean(), nullable=False),
    sa.Column('route_status', sa.Enum('ACTIVE', 'SUSPENDED', 'SEASONAL', name='routestatus'), nullable=False),
    sa.Column('departure_frequency_mins', sa.SmallInteger(), nullable=True),
    sa.Column('avg_duration_mins', sa.SmallInteger(), nullable=True),
    sa.Column('peak_duration_mins', sa.SmallInteger(), nullable=True),
    sa.Column('fare_last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['dest_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['origin_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['sacco_id'], ['saccos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sacco_aliases',
    sa.Column('sacco_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('alias_type', sa.Enum('ABBREVIATION', 'COLLOQUIAL', 'FORMER_NAME', name='aliastype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sacco_id'], ['saccos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_hours',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('open_from', sa.Time(), nullable=False),
    sa.Column('open_until', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fare_corrections',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('reported_amount_kes', sa.SmallInteger(), nullable=False),
    sa.Column('fare_type', sa.String(length=50), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='correctionstatus'), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fares',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('fare_type', sa.Enum('PEAK', 'OFF_PEAK', 'LATE_NIGHT', 'WEEKEND', 'PUBLIC_HOLIDAY', name='faretype'), nullable=False),
    sa.Column('day_type', sa.SmallInteger(), nullable=False),
    sa.Column('amount_kes', sa.SmallInteger(), nullable=False),
    sa.Column('valid_from', sa.Time(), nullable=False),
    sa.Column('valid_until', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupancy',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('hour_slot', sa.SmallInteger(), nullable=False),
    sa.Column('avg_load_factor', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'MPESA', 'TAP', name='paymentmethodtype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_alerts',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('SHORT_LOOP', 'DELAYED', 'SUSPENDED_TEMPORARY', 'DIVERSION', name='alerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_sw', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_paths',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('stop_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('leg1_route_id', sa.UUID(), nullable=False),
    sa.Column('leg2_route_id', sa.UUID(), nullable=False),
    sa.Column('transfer_stage_id', sa.UUID(), nullable=False),
    sa.Column('avg_wait_mins', sa.SmallInteger(), nullable=True),
    sa.Column('total_fare_kes', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['leg1_route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['leg2_route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['transfer_stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('route_paths')
    op.drop_table('route_alerts')
    op.drop_table('payment_methods')
    op.drop_table('occupancy')
    op.drop_table('fares')
    op.drop_table('fare_corrections')
    op.drop_table('stage_hours')
    op.drop_table('sacco_aliases')
    op.drop_table('routes')
    op.drop_table('corridor_surges')
    op.drop_table('stages')
    op.drop_table('search_logs')
    op.drop_table('saccos')
    op.drop_table('public_holidays')
    op.drop_table('corridors')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
